GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('dual_chambered_vacuum_complex', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuum_chemical_reaction_chamber')
        .recipeModifiers([$StarTRecipeModifiers.THOUGHPUT_BOOSTING, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(() => Block.getBlock('kubejs:enriched_naquadah_firebox_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aabaacdddddc", "acccaccbbbbc", "bcccbccbbbcc", "bcccaccccccc", "aabaaccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc")
            .aisle("abbbacdddddd", "bfffbcbcccbc", "bfgfbcbcccbc", "bfffbcjbbbjc", "abbbacjbcbjc", "ccbcccjbcbjc", "ccbcccjbcbjc", "ccccccjbcbjc", "ccccccbbbbbc", "cccccccccccc", "cccccccccccc")
            .aisle("dddddddddddd", "bcccbbcccccb", "bcccbbcccccb", "bcccbcbfffbc", "bbbbbcbfhfbc", "cbbbccbfhfbc", "cbbbccbfhfbc", "ccbcccbfhfbc", "ccbcccbfffbc", "cccccccccccc", "cccccccccccc")
            .aisle("dddddddddddd", "bcccbbcccccb", "bcccbbcccccb", "bcccbbbfffbc", "bbcbbbbfchcc", "bbcbbcbfchcc", "bbibbcbfchcc", "cbibccbfchcc", "cbibccbfifbc", "cciccccciccc", "cciiiiiiiccc")
            .aisle("dddddddddddd", "bcccbbcccccb", "bcccbbcccccb", "bcccbcbfffbc", "bbbbbcbfhfbc", "cbbbccbfhfbc", "cbbbccbfhfbc", "ccbcccbfhfbc", "ccbcccbfffbc", "cccccccccccc", "cccccccccccc")
            .aisle("abbbaddddddd", "bfffbcbcccbc", "bfgfbcbcccbc", "bfffbcabbbac", "abbbacabcbac", "ccbcccabcbac", "ccbcccabcbac", "ccccccabcbac", "ccccccbbbbbc", "cccccccccccc", "cccccccccccc")
            .aisle("aabaacdddddc", "acccaccbebcc", "bcccbccbbbcc", "acccaccccccc", "aabaaccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc", "cccccccccccc")
            .where("a", Predicates.blocks("gtceu:red_steel_frame"))
            .where("b", Predicates.blocks("kubejs:enriched_naquadah_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)).setMinGlobalLimited(1)
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities($StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0)))
            .where("c", Predicates.any())
            .where("d", Predicates.blocks("kubejs:enriched_naquadah_firebox_casing"))
            .where("e", Predicates.controller(Predicates.blocks(definition.get())))
            .where("f", Predicates.blocks("kubejs:polycarbonate_casing"))
            .where("g", $StarTVacuumPumpPredicates.vacuumPumps())
            .where("h", Predicates.blocks("kubejs:reinforced_fusion_glass"))
            .where("i", Predicates.blocks("kubejs:enriched_naquadah_pipe_casing"))
            .where("j", Predicates.blocks("gtceu:void_frame"))
            .build())
         .workableCasingModel("kubejs:block/casings/naquadah/casing", "gtceu:block/machines/chemical_reactor");
        
});