GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('arboreal_vacuum_imacination', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('vacuum_chemical_reaction_chamber')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT])
        .appearanceBlock(() => Block.getBlock('kubejs:absolute_annihilation_casing'))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaabbbhbbbaaaaaa", "aaaaabaaabaaabaaaaa", "aaaaabaaabaaabaaaaa", "aaaaabaaabaaabaaaaa", "aaaaaabbbibbbaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
            .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaacccbcccaaaaaa", "aaaacccccbcccccaaaa", "aaccccaaabaaaccccaa", "aaccccaaabaaaccccaa", "aaccccaaabaaaccccaa", "aaaacccccbcccccaaaa", "aaaaaacccbcccaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aaaaaacccbcccaaaaaa", "aaaaccaaaaaaaccaaaa", "aabbbbbbbbbbbbbbbaa", "bbbbbbdddbdddbbbbbb", "bbbbbbdddbdddbbbbbb", "bbbbbbdddbdddbbbbbb", "aabbbbbbbbbbbbbbbaa", "aaaaccaaaaaaaccaaaa", "aaaaaacccbcccaaaaaa", "aaaaaaaaabaaaaaaaaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aaaacccccbcccccaaaa", "aabbaaaaaaaaaaabbaa", "bbbbbbbebbbebbbbbbb", "aabbbbaaabaaabbbbaa", "aabbbfaaabaaafbbbaa", "aabbbbaaabaaabbbbaa", "bbbbbbbebbbebbbbbbb", "aabbaaaaaaaaaaabbaa", "aaaacccccbcccccaaaa", "aaaaaaabbbbbaaaaaaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aacccccccbcccccccaa", "bbaaaaaaaaaaaaaaabb", "aabbbbbebbbebbbbbaa", "aaabbbaaabaaabbbaaa", "aaaabfaaabaaafbaaaa", "aaabbbaaabaaabbbaaa", "aabbbbbebbbebbbbbaa", "bbbbaaaaaaaaaaabbbb", "aacccccccbcccccccaa", "aaaaabbbbbbbbbaaaaa")
            .aisle("aabbbbbbbbbbbbbbbaa", "bbcccccccbcccccccbb", "bbaaaaaaaaaaaaaaabb", "aabbbbbebbbebbbbbaa", "aaaabbaaabaaabbaaaa", "aaaagfaaabaaafgaaaa", "aaaabbaaabaaabbaaaa", "aabbbbbebbbebbbbbaa", "bbbbaaaaaaaaaaabbbb", "bbcccccccbcccccccbb", "aabbbbbbbbbbbbbbbaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aacccccccbcccccccaa", "bbaaaaaaaaaaaaaaabb", "aabbbbbebbbebbbbbaa", "aaabbbaaabaaabbbaaa", "aaaabfaaabaaafbaaaa", "aaabbbaaabaaabbbaaa", "aabbbbbebbbebbbbbaa", "bbbbaaaaaaaaaaabbbb", "aacccccccbcccccccaa", "aaaaabbbbbbbbbaaaaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aaaacccccbcccccaaaa", "aabbaaaaaaaaaaabbaa", "bbbbbbbebbbebbbbbbb", "aabbbbaaabaaabbbbaa", "aabbbfaaabaaafbbbaa", "aabbbbaaabaaabbbbaa", "bbbbbbbebbbebbbbbbb", "aabbaaaaaaaaaaabbaa", "aaaacccccbcccccaaaa", "aaaaaaabbbbbaaaaaaa")
            .aisle("aaaaaaaaabaaaaaaaaa", "aaaaaacccbcccaaaaaa", "aaaaccaaaaaaaccaaaa", "aabbbbbbbbbbbbbbbaa", "bbbbbbdddbdddbbbbbb", "bbbbbbdddbdddbbbbbb", "bbbbbbdddbdddbbbbbb", "aabbbbbbbbbbbbbbbaa", "aaaaccaaaaaaaccaaaa", "aaaaaacccbcccaaaaaa", "aaaaaaaaabaaaaaaaaa")
            .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaacccbcccaaaaaa", "aaaacccccbcccccaaaa", "aaccccaaabaaaccccaa", "aaccccaaabaaaccccaa", "aaccccaaabaaaccccaa", "aaaacccccbcccccaaaa", "aaaaaacccbcccaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
            .aisle("aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaabbbbbbbaaaaaa", "aaaaabaaabaaabaaaaa", "aaaaabaaabaaabaaaaa", "aaaaabaaabaaabaaaaa", "aaaaaabbbbbbbaaaaaa", "aaaaaaaaabaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa")
            .where("a", Predicates.any())
            .where("b", Predicates.blocks("kubejs:absolute_annihilation_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2)).setMinGlobalLimited(1)
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities($StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1)))
            .where("c", Predicates.blocks("kubejs:inoculated_nuclei_seperation_casing"))
            .where("d", Predicates.blocks("kubejs:draco_resilient_fusion_glass"))
            .where("e", Predicates.blocks("kubejs:lumium_casing"))
            .where("f", Predicates.blocks("kubejs:nyanium_pipe_casing"))
            .where("g", $StarTVacuumPumpPredicates.vacuumPumps())
            .where("h", Predicates.controller(Predicates.blocks(definition.get())))
            .where("i", Predicates.blocks("start_core:uiv_parallel_hatch"))
            .build())
        .workableCasingModel('kubejs:block/casings/abydos_multis/absolute_annihilation_casing',
            'kubejs:block/multiblock/primitive_blast_furnace');
        
});